### ISSUE TITLE
大佬有没有兴趣做个能自动生成红石电路的软件

### ISSUE THREAD

**Issue by EnderTheCoder** [ARS-MC/RRDC#1]
就像EDA那种的，可以快速生成一些集成电路并且导入到地图中，这肯定会很有趣，大大节省建造一些红石计算器这种设施的时间。我之前一直有这个想法，奈何不会硬件也因为高考没时间了。

**Comment by NKID00** [comment]
> 就像EDA那种的，可以快速生成一些集成电路并且导入到地图中，这肯定会很有趣，大大节省建造一些红石计算器这种设施的时间。我之前一直有这个想法，奈何不会硬件也因为高考没时间了。

https://github.com/itsFrank/MinecraftHDL

试试这个？
